### ISSUE TITLE
JSON web API

### ISSUE THREAD

**Issue by rugk** [Aaronepower/tokei_rs#8]
You support [generating badges](https://github.com/Aaronepower/tokei#badges), but a more general web API with JSON output or so would be nice.

The use case is that this can then be used in [shields](https://github.com/badges/shields/), which also has different badge styles etc. See issue https://github.com/badges/shields/issues/2731.

**Comment by Aaronepower** [comment]
Thank you for your issue! I have now implemented this in tokei.rs if you change your Accept HTTP header to `application/json` you will receive JSON data. The files seem to be currently missing in production, but work locally so you can't use that info yet but that will be fixed soon.

**Comment by Aaronepower** [comment]
The bugs mentioned have since been fixed.
